language: scala
scala:
    - 2.12.4
    - 2.11.12
    
jdk:
    - oraclejdk8

before_cache:
    - find $HOME/.sbt -name "*.lock" | xargs rm
    - find $HOME/.ivy2 -name "ivydata-*.properties" | xargs rm

cache:
    directories:
        - $HOME/.ivy2/cache/
        - $HOME/.sbt/boot/

script:
    - SBT_OPTS="-Xms512M -Xmx2G -Xss2M -XX:MaxMetaspaceSize=1024M" sbt ++$TRAVIS_SCALA_VERSION scalastyle test headerCheck test:headerCheck it:test doc

notifications:
  email: false
