#osx is needed to get the same buffered images
os: osx

language: scala
    
jdk: oraclejdk8

scala: 
  - 2.12.4
    #- 2.11.12

# Use container-based infrastructure
sudo: false

before_cache:
    # Cleanup the cached directories to avoid unnecessary cache updates
    - find $HOME/.sbt        -name "*.lock"               -print -delete
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete

cache:
    directories:
        - $HOME/.ivy2/cache/
        - $HOME/.sbt/boot/

script:
   #- sbt ++$TRAVIS_SCALA_VERSION scalastyle test headerCheck test:headerCheck it:test doc
   - sbt ++$TRAVIS_SCALA_VERSION it:test

notifications:
  email: false
