language: scala
    
jdk: oraclejdk8


before_cache:
    # Cleanup the cached directories to avoid unnecessary cache updates
    - find $HOME/.sbt        -name "*.lock"               -print -delete
    - find $HOME/.ivy2/cache -name "ivydata-*.properties" -print -delete

cache:
    directories:
        - $HOME/.ivy2/cache/
        - $HOME/.sbt/boot/

script:
   - sbt + scalastyle test headerCheck test:headerCheck it:test doc

notifications:
  email: false
